wk6/dy1-rails-associations/tunr_associations_app/config/routes.rb
Rails.application.routes.draw do

    resources :artists
    resources :albums
    resources :songs

    get 'artists/:id/:album_id', to: 'artists#show_albums'

    root 'artists#index'

end

wk6/dy1-rails-associations/tunr_associations_app/app/models/album.rb
class Album < ActiveRecord::Base
  has_many :album_songs
  has_many :songs, through: :album_songs, dependent: :destroy
end

wk6/dy1-rails-associations/tunr_associations_app/app/models/album_song.rb
class AlbumSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :album
end

wk6/dy1-rails-associations/tunr_associations_app/app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

wk6/dy1-rails-associations/tunr_associations_app/app/models/song.rb
class Song < ActiveRecord::Base
  has_many :album_songs
  has_many :albums, through: :album_songs, dependent: :destroy
  belongs_to :artist

  validates :title, presence: true
  validates :title, uniqueness: true
end

wk6/dy1-rails-associations/tunr_associations_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    

    @albums = Album.all
  end
end

wk6/dy1-rails-associations/tunr_associations_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

wk6/dy1-rails-associations/tunr_associations_app/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

end

wk6/dy1-rails-associations/tunr_associations_app/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
    @artists = Artist.all
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to @song
    else
      render :new
    end
  end


  private

  def song_params
    params.require(:song).permit(:title, :artist_id)
  end

end

wk6/dy1-rails-associations/tunr_associations_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

wk6/dy1-rails-associations/tunr_associations_app/app/helpers/application_helper.rb
module ApplicationHelper
end

wk6/dy1-rails-associations/tunr_associations_app/app/helpers/artists_helper.rb
module ArtistsHelper
end

wk6/dy1-rails-associations/tunr_associations_app/app/helpers/songs_helper.rb
module SongsHelper
end

wk6/dy1-rails-associations/tunr_associations_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TunrAssociationsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

wk6/dy1-rails-associations/tunr_associations_app/app/views/songs/index.html.erb
<div>
  <ul>
  <% @songs.each do |song| %>
    <li><%= link_to(song.title, song_path(song.id))%></li>
  <% end %>
  </ul>
</div>

wk6/dy1-rails-associations/tunr_associations_app/app/views/songs/new.html.erb
<%= form_for @song do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :artist_id %>
    <%= form.select :artist_id, options_from_collection_for_select(@artists, 'id','name') %>
   <!--  ?f.collection)select (:artist_id,  -->)
  </div>

  <div class="action">
    <%= form.submit 'New Song' %>
  </div>
<% end %>

wk6/dy1-rails-associations/tunr_associations_app/app/views/songs/show.html.erb
<h1><%=@song.title%></h1>


<p>Albums that this song is on:</p>
<ul>
  <% @song.albums.each do |album| %>
    <li><%= link_to(album.name, album) %></li>
  <% end %>
</ul>