wk6/dy2/street_gallery_app/config/routes.rb
Rails.application.routes.draw do
  resources :locations

  root 'locations#index'

end

wk6/dy2/street_gallery_app/app/models/location.rb
class Location < ActiveRecord::Base
  mount_uploader :graffiti_image, GraffitiImageUploader
end

wk6/dy2/street_gallery_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

wk6/dy2/street_gallery_app/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :graffiti_image)
    end
end

wk6/dy2/street_gallery_app/app/helpers/application_helper.rb
module ApplicationHelper
end

wk6/dy2/street_gallery_app/app/helpers/locations_helper.rb
module LocationsHelper
end

wk6/dy2/street_gallery_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StreetGalleryApp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'shared/header' %>

<%= yield %>

<%= render partial: 'shared/footer' %>

</body>
</html>

wk6/dy2/street_gallery_app/app/views/shared/_footer.html.erb
<footer>

  <br/>
<div align="center" class="socialbtns">
  <ul>
  <li><a href="#" class="fa fa-lg fa-facebook"></a></li>
  <li><a href="#" class="fa fa-lg fa-twitter"></a></li>
  <li><a href="#" class="fa fa-lg fa-google-plus"></a></li>
  <li><a href="#" class="fa fa-lg fa-github"></a></li>
  <li><a href="#" class="fa fa-lg fa-pinterest"></a></li>
  <li><a href="#" class="fa fa-lg fa-linkedin"></a></li>
  <li><a href="#" class="fa fa-lg fa-instagram"></a></li>
  <li><a href="#" class="fa fa-lg fa-youtube"></a></li>
  </ul>
  </div>

</footer>

wk6/dy2/street_gallery_app/app/views/shared/_header.html.erb
<header>
  <nav>
    <li> <%= link_to('locations', locations_path )%></li>
    <li><%= link_to('Create location', new_location_path) %></li>
    <!-- NB look in rake routes to get paths -->
  </nav>
</header>